### PR TITLE
Adopt typedoc for API docs

### LINKED ISSUE #63: [chore] Adopt typedoc for API docs
We've used it on another project ([vastly](https://github.com/mavoweb/vastly/)) and it's far superior to the one we're using here, which never worked properly for Madata. We did not have to switch to TS to use it, it works with JSDoc too (though I think @adamjanicki2 had to do some config to get it to work without TS)

### PR DESCRIPTION
**Pull request by DmitrySharabin**
Closes #63.

The docs are **much** better now! 🤩

https://deploy-preview-66--madata.netlify.app/api/

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks for working on this!
Some Qs:
- Is there a way to use Prism instead of whatever this is using for syntax highlighting?
- It's also parsing our README.md and displaying it, but not any of the other READMEs or other Markdown files. I wonder if that's possible to enable somehow.
- How can we make CSS customizations? Might be a good idea to include a CSS stub file

**Comment by DmitrySharabin** [comment]
> Thanks for working on this!
> 
> Some Qs:
> 
> - Is there a way to use Prism instead of whatever this is using for syntax highlighting?
> 
> - It's also parsing our README.md and displaying it, but not any of the other READMEs or other Markdown files. I wonder if that's possible to enable somehow.
> 
> - How can we make CSS customizations? Might be a good idea to include a CSS stub file 

Good questions. Will dig into typedoc a bit. There might be something in there that we can use.

**Comment by DmitrySharabin** [comment]
> How can we make CSS customizations? Might be a good idea to include a CSS stub file

We can have a custom CSS file, which [will be referenced](https://typedoc.org/options/output/#customcss) in the `typedoc.json` file.

How would we call it? `api.css`?

Where should we place it? In the root? In the `_build` folder? Inside `_include`? Somewhere else? It will be copied into the `assets` directory and referenced by the API docs theme.

**Comment by DmitrySharabin** [comment]
> It's also parsing our README.md and displaying it, but not any of the other READMEs or other Markdown files. I wonder if that's possible to enable somehow.

This is [planned to be in the core](https://github.com/TypeStrong/typedoc/issues/1870) (hopefully) soon.

Until then, there is a [plugin](https://github.com/KnodesCommunity/typedoc-plugins/tree/develop/packages/plugin-pages) that might help us get the desired result. But there is much hand work involved. Should we try to use it?

**Comment by LeaVerou** [comment]
> > How can we make CSS customizations? Might be a good idea to include a CSS stub file
> 
> We can have a custom CSS file, which [will be referenced](https://typedoc.org/options/output/#customcss) in the `typedoc.json` file.
> 
> How would we call it? `api.css`?
> 
> Where should we place it? In the root? In the `_build` folder? Inside `_include`? Somewhere else? It will be copied into the `assets` directory and referenced by the API docs theme.

We can start with `api.css` in the root for now, and move it when we move the website CSS

**Comment by LeaVerou** [comment]
> > It's also parsing our README.md and displaying it, but not any of the other READMEs or other Markdown files. I wonder if that's possible to enable somehow.
> 
> This is [planned to be in the core](https://github.com/TypeStrong/typedoc/issues/1870) (hopefully) soon.
> 
> Until then, there is a [plugin](https://github.com/KnodesCommunity/typedoc-plugins/tree/develop/packages/plugin-pages?rgh-link-date=2024-01-21T00%3A00%3A17Z) that might help us get the desired result. But there is much hand work involved. Should we try to use it?

We don't need typedoc for our own docs, but it would be nice to have it for the individual READMEs within each backend/format/etc. Can we use a different MD file than README.md for the root? It seems very weird to duplicate our homepage content there.

Would it be easier to automate the handwork involved?

**Comment by DmitrySharabin** [comment]
> Can we use a different MD file than README.md for the root? It seems very weird to duplicate our homepage content there.

We can. I just pushed the commit, which allows us to use `API.md` (we can rename and re-locate it later if needed) as a custom index (root) page for the API docs.

> Would it be easier to automate the handwork involved?

I'm sure it would. 😅 Will give it a try.

**Comment by DmitrySharabin** [comment]
Digging a bit further into the problem of generating doc pages from our READMEs, I learned that the plugin I was going to use for this [doesn't work with the latest version of typedoc](https://github.com/KnodesCommunity/typedoc-plugins/issues/369). 😭 Nor do other plugins from which that one was forked. I will try to find alternative solutions. 🤞

**Comment by DmitrySharabin** [comment]
> Dmitry, let's merge this since it's clearly better than the current state, then we can improve it later. Do you agree?

Absolutely! I almost lost my mind trying to find a way to make it work we wanted. 😅

**Pull request merged**
